export const tabData = {
  products: [
    {
      id: 1,
      category_id: 1,
      name: "Lux Full Ortopet Korean",
      category: "Model A+",
      product_images: "/product/ortopedic.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      new_cost: "120000",
      status: "3",
      is_active: "1",
    },

    {
      id: 2,
      category_id: 1,
      name: "Ortopedik Eko matras",
      category: "Model C+",
      product_images: "/product/lux.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "250000",
      new_cost: "140000",
      status: "3",
      is_active: "1",
    },
    {
      id: 3,
      category_id: 1,
      name: "Lux Full Ortopet Korean",
      category: "Model A+",
      product_images: "/product/ortopedic.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 4,
      category_id: 2,
      name: "Ortopedik Eko matras",
      category: "Model B+",
      product_images: "/product/lux.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 5,
      category_id: 3,
      name: "Lux Full Ortopet Korean",
      category: "Model C",
      product_images: "/product/ortopedic.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 6,
      category_id: 4,
      name: "Lux Full Ortopet Korean",
      category: "Model C+",
      product_images: "/product/lux.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 7,
      category_id: 5,
      name: "Ortopedik Eko matras",
      category: "Model D",
      product_images: "/product/lux.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "300000",
      new_cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 8,
      category_id: 6,
      name: "Lux Full Ortopet Korean",
      category: "Model Yevro",
      product_images: "/product/lux.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 9,
      category_id: 7,
      name: "Ortopedik Eko matras",
      category: "Yangi tovarlar",
      product_images: "/product/ortopedic.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
    {
      id: 10,
      category_id: 8,
      name: "Lux Full Ortopet Korean",
      category: "Model A",
      product_images: "/product/lux.png",
      weight: 70,
      warranty: 2,
      size: "200 x 160 x 45",
      capacity: 2,
      body: "Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.",
      cost: "200000",
      status: "3",
      is_active: "1",
    },
  ],
  categories: [
    {
      id: 0,
      category: "Barchasi",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 1,
      category: "Model A+",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 2,
      category: "Model B+",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 3,
      category: "Model C",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 4,
      category: "Model C+",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 5,
      category: "Model D",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 6,
      category: "Model Yevro",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 7,
      category: "Yangi tovarlar",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
    {
      id: 8,
      category: "Model A",
      time: "2023-07-01 15:54:47",
      is_active: "1",
    },
  ],
};
